# Generated by Django 5.2.1 on 2025-06-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='mass',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='number_of_animals',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
